version: "3"
services:
  api:
    links:
      - mysql
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./api:/go/src/api
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
    hostname: mysql
    ports: 
      - "3306:3306"
